'''Manage all logs generated by sherlock stream'''
import logging

from sherlock.sherlock_types import TYPES

SHERLOCK_LOG_LEVEL = 9999

class Log4Sherlock:


    def __init__(self, handler = logging.FileHandler('sherlock.log')):

        self._logger = logging.getLogger(name='SHERLOCK')
        self._logger.addFilter(SherlockLogFilter())
        self._handler = handler
        self._logger.addHandler(handler)


    def startLogger(self):

        logging.basicConfig(format='%(message)s', level=SHERLOCK_LOG_LEVEL)
        self.getLogger().log(SHERLOCK_LOG_LEVEL, 'Sherlock Stream Logging Started')


    def getLogger(self):
        return self._logger


class SherlockLogFilter(logging.Filter):


    def filter(self, record):
        message = record.getMessage()
        for ssTypes in TYPES:
            if message.startswith(ssTypes):
                return True
        return False


if __name__ == '__main__':
    Log4Sherlock().startLogger()